name: flutter_sound
version: 8.3.0
description: A complete api for audio playback and recording. Audio player, audio recorder, media player, media recorder, sound player, sound recorder.
#author: dooboolab<dooboolab@gmail.com>
homepage: https://tau.canardoux.xyz/readme.html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  #pedantic: ^1.11.0

  path_provider: ^2.0.1
  recase: ^4.0.0
  uuid: ^3.0.1
  provider: ^6.0.1
  flutter_spinkit: ^5.0.0
  path: ^1.8.0
  synchronized: ^3.0.0
  logger: ^1.0.0
  #flutter_ffmpeg: ^0.3.1
  flutter:
    sdk: flutter
# ============================================================================
  flutter_sound_platform_interface: 8.2.0
#    path: ../flutter_sound_platform_interface # Flutter Sound Dir
#  flutter_sound_web: 8.2.0
#    path: ../flutter_sound_web # Flutter Sound Dir
# ============================================================================

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  pedantic: ^1.11.0
  #effective_dart: ^1.3.0
  #lint: ^1.1.1



# For information on the generic Dart part of this file, see the
# following page: https:/www/canardoux.xyz/tau_sound/doc.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.dooboolab.fluttersound
        pluginClass: FlutterSound
      ios:
        pluginClass: FlutterSound
      web:
        default_package: flauto_web
        ####fileName: flutter_sound_web.dart


  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
