# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'PunchCardTogether' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HyphenateChat'
  pod 'GRDB.swift'
  pod 'Moya/Combine'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'ToastSwiftUI'
  pod 'Toast'
  pod 'Introspect'
  pod 'ReactorKit'
  pod 'RxDataSources'
  pod 'RxKeyboard'
  pod 'SnapKit'
  pod 'Reusable'
  pod 'RxViewController'
  pod 'GrowingTextView'
  pod 'SVProgressHUD'
  # Pods for PunchCardTogether

  target 'PunchCardTogetherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PunchCardTogetherUITests' do
    # Pods for testing
  end

end
